### ISSUE TITLE
some problems in build server

### ISSUE THREAD

**Issue by zbximo** [agentlabs-inc/agentlabs#3]
when i excute " bash build-clients.sh ",  it's falied because of '--yes'. Next, i remove '--yes', i got the error message ''npx: installed 20 in 3.898s Unexpected token {". How can i solve it ?

**Comment by kevinpiac** [comment]
Thanks for creating this first issue!

Glad to have you eager of testing this.

As it's specified in the README, this repository is under active development and now ready to use at the moment.
Moreover it will considerably change in the next few days.

I strongly suggest you wait for the alpha version that will rollout very soon! :)

**Comment by kevinpiac** [comment]
Just added some info in the readme to make it clearer: 

https://github.com/agentlabs-inc/agentlabs#alpha-release
