### ISSUE TITLE
AttributeError: 'Agent' object has no attribute 'request_login'

### ISSUE THREAD

**Issue by hitz02** [agentlabs-inc/agentlabs#56]
Hi @kevinpiac @aurelien-brabant , is the login feature implemented for python sdk?
I am trying to implement something similar to your `chat-with-rust-book example` and would like to enforce login

I get `AttributeError: 'Agent' object has no attribute 'request_login'` when tried with below code snippet

```
# in main
ferris = agentlabs.agent(env.agent_id)

# in handle_chat_message
ferris.request_login(
            conversation_id=message.conversation_id,
            text="Please login to access this feature"
            )
```

**Comment by kevinpiac** [comment]
Hi @hitz02!

Thanks for reporting this. It's right, the documentation is a bit ahead of our codebase. The Python SDK currently does not support this feature.

Good news though, we're going to ship it today or tomorrow :)

I will keep you updated here!

**Comment by hitz02** [comment]
Thanks for the update @kevinpiac, any update on paywall feature to monetize agents?

**Comment by hitz02** [comment]
Thanks for releasing a new update, and I've DM'ed you on Discord

**Comment by hitz02** [comment]
Also, can you share a simple e2e example on how to use `request_login` ?
